version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"   # Only expose Laravel app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: multi_food_db
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_DATABASE: multi_food_db
      MYSQL_ROOT_PASSWORD: root
    command: --default-time-zone='+00:00'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-net


  redis:
    image: redis:7
    container_name: laravel-redis
    restart: always
    networks:
      - laravel-net

volumes:
  mysql_data:

networks:
  laravel-net:
